/**
 * Created by lap-hep-deb-use on 1/19/17.
 */
var names = {
    "ae": "s:President: Sheikh Khalifa bin Zayed Al Nahyan | g:Prime Minister: Sheikh Mohammed bin Rashid Al Maktoum",
    "af": "s:President: Ashraf Ghani | g:Chief Executive Officer: Abdullah Abdullah",
    "ag": "s:Queen: Elizabeth II, Governor-General: Sir Rodney Williams | g:Prime Minister: Gaston Browne",
    "al": "s:President: Bujar Nishani | g:Prime Minister: Edi Rama",
    "am": "s:President: Serzh Sargsyan | g:Prime Minister: Karen Karapetyan",
    "ao": "s:President: José Eduardo dos Santos",
    "ar": "s:President: Mauricio Macri",
    // "at": "s:Federal President: Vacant, Federal President-elect: Alexander Van der Bellen, Acting Federal Presidential college:Member: Doris Bures, Member: Karlheinz Kopf, Member: Norbert Hofer | g:Federal Chancellor: Christian Kern",
    "at": "s:Federal President: Alexander Van der Bellen | g:Federal Chancellor: Christian Kern",
    "au": "s:Queen: Elizabeth II, Governor-General: Sir Peter Cosgrove | g:Prime Minister: Malcolm Turnbull",
    "az": "s:President: Ilham Aliyev | g:Prime Minister: Artur Rasizade",
    // "ba": "s:High Representative: Valentin Inzko, Chairman: Mladen Ivanić, Member: Dragan Čović, Member: Bakir Izetbegović | g:Chairman of the Council of Ministers: Denis Zvizdić",
    "ba": "s:High Representative: Valentin Inzko, Chairman: Mladen Ivanić | g:Chairman of the Council of Ministers: Denis Zvizdić",
    "bb": "s:Queen: Elizabeth II, Governor-General: Sir Elliott Belgrave | g:Prime Minister: Freundel Stuart",
    "bd": "s:President: Abdul Hamid | g:Prime Minister: Sheikh Hasina",
    "be": "s:King: Philippe | g:Prime Minister: Charles Michel",
    "bf": "s:President: Roch Marc Christian Kaboré | g:Prime Minister: Paul Kaba Thieba",
    "bg": "s:President-elect: Rumen Radev | g:Prime Minister: Boyko Borissov",
    "bi": "s:President: Pierre Nkurunziza",
    "bj": "s:President: Patrice Talon",
    "bn": "s:Sultan and Prime Minister: Hassanal Bolkiah",
    "bo": "s:President: Evo Morales",
    "br": "s:President: Michel Temer",
    "bs": "s:Queen: Elizabeth II, Governor-General: Dame Marguerite Pindling | g:Prime Minister: Perry Christie",
    "bt": "s:King: Jigme Khesar Namgyel Wangchuck | g:Prime Minister: Tshering Tobgay",
    "bw": "s:President: Ian Khama",
    "by": "s:President: Alexander Lukashenko | g:Prime Minister: Andrei Kobyakov",
    "bz": "s:Queen: Elizabeth II, Governor-General: Sir Colville Young | g:Prime Minister: Dean Barrow",
    "ca": "s:Queen: Elizabeth II, Governor General: David Johnston | g:Prime Minister: Justin Trudeau",
    "cd": "s:President: Joseph Kabila | g:Prime Minister: Samy Badibanga",
    "cf": "s:President: Faustin-Archange Touadéra | g:Prime Minister: Simplice Sarandji",
    "cg": "s:President: Denis Sassou Nguesso | g:Prime Minister: Clément Mouamba",
    // "ch": "s:President: Doris Leuthard, Vice President: Alain Berset, Member: Ueli Maurer, Member: Didier Burkhalter, Member: Simonetta Sommaruga, Member: Johann Schneider-Ammann, Member: Guy Parmelin",
    "ch": "s:President: Doris Leuthard, Vice President: Alain Berset",
    "ci": "s:President: Alassane Ouattara | g:Prime Minister: Amadou Gon Coulibaly",
    "cl": "s:President: Michelle Bachelet",
    "cm": "s:President: Paul Biya | g:Prime Minister: Philémon Yang",
    "cn": "s:General Secretary of the Communist Party: Xi Jinping, President: Xi Jinping | g:Premier of the State Council: Li Keqiang",
    "co": "s:President: Juan Manuel Santos",
    "cr": "s:President: Luis Guillermo Solís",
    "cu": "s:First Secretary of the Communist Party: Raúl Castro, President of the Council of State and President of the Council of Ministers: Raúl Castro",
    "cv": "s:President: Jorge Carlos Fonseca | g:Prime Minister: Ulisses Correia e Silva",
    "cy": "s:President: Nicos Anastasiades",
    "cz": "s:President: Miloš Zeman | g:Prime Minister: Bohuslav Sobotka",
    "de": "s:President: Joachim Gauck | g:Chancellor: Angela Merkel",
    "dj": "s:President: Ismaïl Omar Guelleh | g:Prime Minister: Abdoulkader Kamil Mohamed",
    "dk": "s:Queen: Margrethe II | g:Prime Minister: Lars Løkke Rasmussen",
    "dm": "s:President: Charles Savarin | g:Prime Minister: Roosevelt Skerrit",
    "do": "s:President: Danilo Medina",
    "dz": "s:President: Abdelaziz Bouteflika | g:Prime Minister: Abdelmalek Sellal",
    "ec": "s:President: Rafael Correa",
    "ee": "s:President: Kersti Kaljulaid | g:Prime Minister: Jüri Ratas",
    "eg": "s:President: Abdel Fattah el-Sisi | g:Prime Minister: Sherif Ismail",
    "er": "s:President: Isaias Afwerki",
    "es": "s:King: Felipe VI | g:President of the Government: Mariano Rajoy",
    "et": "s:President: Mulatu Teshome | g:Prime Minister: Hailemariam Desalegn",
    "fi": "s:President: Sauli Niinistö | g:Prime Minister: Juha Sipilä",
    "fj": "s:President: George Konrote | g:Prime Minister: Frank Bainimarama",
    "fr": "s:President: François Hollande | g:Prime Minister: Bernard Cazeneuve",
    "ga": "s:President: Ali Bongo Ondimba | g:Prime Minister: Emmanuel Issoze-Ngondet",
    "gb": "s:Queen: Elizabeth II | g:Prime Minister: Theresa May",
    "gd": "s:Queen: Elizabeth II, Governor-General: Dame Cécile La Grenade | g:Prime Minister: Keith Mitchell",
    "ge": "s:President: Giorgi Margvelashvili | g:Prime Minister: Giorgi Kvirikashvili",
    "gh": "s:President: Nana Akufo-Addo",
    "gm": "s:President: Adama Barrow",
    "gn": "s:President: Alpha Condé | g:Prime Minister: Mamady Youla",
    "gq": "s:President: Teodoro Obiang Nguema Mbasogo | g:Prime Minister: Francisco Pascual Obama Asue",
    "gr": "s:President: Prokopis Pavlopoulos | g:Prime Minister: Alexis Tsipras",
    "gt": "s:President: Jimmy Morales",
    "gw": "s:President: José Mário Vaz | g:Prime Minister: Umaro Sissoco Embaló",
    "gy": "s:President: David A. Granger | g:Prime Minister: Moses Nagamootoo",
    "hn": "s:President: Juan Orlando Hernández",
    "hr": "s:President: Kolinda Grabar-Kitarović | g:Prime Minister: Andrej Plenković",
    "ht": "s:President-elect: Jovenel Moïse | g:Prime Minister: Enex Jean-Charles",
    "hu": "s:President: János Áder | g:Prime Minister: Viktor Orbán",
    "id": "s:President: Joko Widodo",
    "ie": "s:President: Michael D. Higgins | g:Taoiseach: Enda Kenny",
    "il": "s:President: Reuven Rivlin | g:Prime Minister: Benjamin Netanyahu",
    "in": "s:President: Pranab Mukherjee | g:Prime Minister: Narendra Modi",
    "iq": "s:President: Fuad Masum | g:Prime Minister: Haider al-Abadi",
    "ir": "s:Supreme Leader: Ayatollah Ali Khamenei, President: Hassan Rouhani",
    "is": "s:President: Guðni Th. Jóhannesson | g:Prime Minister: Bjarni Benediktsson",
    "it": "s:President: Sergio Mattarella | g:Prime Minister: Paolo Gentiloni",
    "jm": "s:Queen: Elizabeth II, Governor-General: Sir Patrick Allen | g:Prime Minister: Andrew Holness",
    "jo": "s:King: Abdullah II | g:Prime Minister: Hani Al-Mulki",
    "jp": "s:Emperor: Akihito | g:Prime Minister: Shinzō Abe",
    "ke": "s:President: Uhuru Kenyatta",
    "kg": "s:President: Almazbek Atambayev | g:Prime Minister: Sooronbay Jeenbekov",
    "kh": "s:King: Norodom Sihamoni | g:Prime Minister: Hun Sen",
    "km": "s:President: Azali Assoumani",
    "kn": "s:Queen: Elizabeth II, Governor-General: Sir Tapley Seaton | g:Prime Minister: Timothy Harris",
    "kp": "s:Chairman of the Workers' Party of Korea: Kim Jong-un, Supreme Leader and Chairman of the State Affairs Commission: Kim Jong-un, Chairman of the Presidium of the Supreme People's Assembly: Kim Yong-nam, Premier of the Cabinet: Pak Pong-ju",
    "kr": "s:President: Park Geun-hye, Prime Minister: Hwang Kyo-ahn, Acting President: Hwang Kyo-ahn",
    "kw": "s:Emir: Sheikh Sabah Al-Ahmad Al-Jaber Al-Sabah | g:Prime Minister: Sheikh Jaber Al-Mubarak Al-Hamad Al-Sabah",
    "kz": "s:President: Nursultan Nazarbayev | g:Prime Minister: Bakhytzhan Sagintayev",
    "la": "s:General Secretary of the Communist Party: Bounnhang Vorachith, President: Bounnhang Vorachith | g:Prime Minister: Thongloun Sisoulith",
    "lb": "s:President: Michel Aoun | g:Prime Minister: Saad Hariri",
    "lc": "s:Queen: Elizabeth II, Governor-General: Dame Pearlette Louisy | g:Prime Minister: Allen Chastanet",
    "lk": "s:President: Maithripala Sirisena | g:Prime Minister: Ranil Wickremesinghe",
    "lr": "s:President: Ellen Johnson Sirleaf",
    "ls": "s:King: Letsie III | g:Prime Minister: Pakalitha Mosisili",
    "lt": "s:President: Dalia Grybauskaitė | g:Prime Minister: Saulius Skvernelis",
    "lv": "s:President: Raimonds Vējonis | g:Prime Minister: Māris Kučinskis",
    "ly": "s:Chairman of the Presidential Council and Prime Minister: Fayez al-Sarraj",
    "ma": "s:King: Mohammed VI | g:Head of Government: Abdelilah Benkirane",
    "md": "s:President: Igor Dodon | g:Prime Minister: Pavel Filip",
    "mg": "s:President: Hery Rajaonarimampianina | g:Prime Minister: Olivier Mahafaly Solonandrasana",
    "mk": "s:President: Gjorge Ivanov | g:Interim Prime Minister: Emil Dimitriev, Prime minister-designate: Nikola Gruevski",
    "ml": "s:President: Ibrahim Boubacar Keïta | g:Prime Minister: Modibo Keita",
    "mm": "s:President: Htin Kyaw | g:State Counsellor: Aung San Suu Kyi",
    "mn": "s:President: Tsakhiagiin Elbegdorj | g:Prime Minister: Jargaltulgyn Erdenebat",
    "mr": "s:President: Mohamed Ould Abdel Aziz | g:Prime Minister: Yahya Ould Hademine",
    "mt": "s:President: Marie Louise Coleiro Preca | g:Prime Minister: Joseph Muscat",
    "mu": "s:President: Ameenah Gurib | g:Prime Minister: Sir Anerood Jugnauth",
    "mv": "s:President: Abdulla Yameen",
    "mw": "s:President: Peter Mutharika",
    "mx": "s:President: Enrique Peña Nieto",
    "my": "s:Yang di-Pertuan Agong: Muhammad V | g:Prime Minister: Najib Razak",
    "mz": "s:President: Filipe Nyusi | g:Prime Minister: Carlos Agostinho do Rosário",
    "na": "s:President: Hage Geingob | g:Prime Minister: Saara Kuugongelwa",
    "ne": "s:President: Mahamadou Issoufou | g:Prime Minister: Brigi Rafini",
    "ng": "s:President: Muhammadu Buhari",
    "ni": "s:President: Daniel Ortega",
    "nl": "s:King: Willem-Alexander | g:Prime Minister: Mark Rutte",
    "no": "s:King: Harald V | g:Prime Minister: Erna Solberg",
    "np": "s:President: Bidhya Devi Bhandari | g:Prime Minister: Pushpa Kamal Dahal",
    "nz": "s:Queen: Elizabeth II, Governor-General: Dame Patsy Reddy | g:Prime Minister: Bill English",
    "om": "s:Sultan and Prime Minister: Qaboos bin Said al Said",
    "pa": "s:President: Juan Carlos Varela",
    "pe": "s:President: Pedro Pablo Kuczynski | g:Prime Minister: Fernando Zavala",
    "pg": "s:Queen: Elizabeth II, Governor-General: Sir Michael Ogio | g:Prime Minister: Peter O'Neill",
    "ph": "s:President: Rodrigo Duterte",
    "pk": "s:President: Mamnoon Hussain | g:Prime Minister: Nawaz Sharif",
    "pl": "s:President: Andrzej Duda | g:Prime Minister: Beata Szydło",
    "pt": "s:President: Marcelo Rebelo de Sousa | g:Prime Minister: António Costa",
    "py": "s:President: Horacio Cartes",
    "qa": "s:Emir: Sheikh Tamim bin Hamad Al Thani | g:Prime Minister: Sheikh Abdullah bin Nasser bin Khalifa Al Thani",
    "ro": "s:President: Klaus Iohannis | g:Prime Minister: Sorin Grindeanu",
    "rs": "s:President: Tomislav Nikolić | g:Prime Minister: Aleksandar Vučić",
    "ru": "s:President: Vladimir Putin | g:Prime Minister: Dmitry Medvedev",
    "rw": "s:President: Paul Kagame | g:Prime Minister: Anastase Murekezi",
    "sa": "s:King and Prime Minister: Salman",
    "sb": "s:Queen: Elizabeth II, Governor-General: Sir Frank Kabui | g:Prime Minister: Manasseh Sogavare",
    "sc": "s:President: Danny Faure",
    "sd": "s:President: Omar al-Bashir",
    "se": "s:King: Carl XVI Gustaf | g:Prime Minister: Stefan Löfven",
    "si": "s:President: Borut Pahor | g:Prime Minister: Miro Cerar",
    "sk": "s:President: Andrej Kiska | g:Prime Minister: Robert Fico",
    "sl": "s:President: Ernest Bai Koroma",
    "sn": "s:President: Macky Sall | g:Prime Minister: Mohammed Dionne",
    "so": "s:President: Hassan Sheikh Mohamud | g:Prime Minister: Omar Abdirashid Ali Sharmarke",
    "sr": "s:President: Dési Bouterse",
    "ss": "s:President: Salva Kiir Mayardit",
    "st": "s:President: Evaristo Carvalho | g:Prime Minister: Patrice Trovoada",
    "sv": "s:President: Salvador Sánchez Cerén",
    "sy": "s:President: Bashar al-Assad | g:Prime Minister: Imad Khamis",
    "sz": "s:King: Mswati III | g:Prime Minister: Barnabas Sibusiso Dlamini",
    "td": "s:President: Idriss Déby | g:Prime Minister: Albert Pahimi Padacké",
    "tg": "s:President: Faure Gnassingbé | g:Prime Minister: Komi Sélom Klassou",
    "th": "s:King: Maha Vajiralongkorn | g:Prime Minister: Prayut Chan-o-cha",
    "tj": "s:President: Emomali Rahmon | g:Prime Minister: Kokhir Rasulzoda",
    "tl": "s:President: Taur Matan Ruak | g:Prime Minister: Rui Maria de Araújo",
    "tm": "s:President: Gurbanguly Berdimuhamedow",
    "tn": "s:President: Beji Caid Essebsi | g:Head of Government: Youssef Chahed",
    "tr": "s:President: Recep Tayyip Erdoğan | g:Prime Minister: Binali Yıldırım",
    "tt": "s:President: Anthony Carmona | g:Prime Minister: Keith Rowley",
    "tz": "s:President: John Magufuli | g:Prime Minister: Kassim Majaliwa",
    "ua": "s:President: Petro Poroshenko | g:Prime Minister: Volodymyr Groysman",
    "ug": "s:President: Yoweri Museveni | g:Prime Minister: Ruhakana Rugunda",
    "us": "s:President: Donald Trump",
    "uy": "s:President: Tabaré Vázquez",
    "uz": "s:President: Shavkat Mirziyoyev | g:Prime Minister: Abdulla Aripov",
    "vc": "s:Queen: Elizabeth II, Governor-General: Sir Frederick Ballantyne | g:Prime Minister: Ralph Gonsalves",
    "ve": "s:President: Nicolás Maduro",
    "vn": "s:General Secretary of the Communist Party: Nguyễn Phú Trọng, President: Trần Đại Quan, Prime Minister: Nguyễn Xuân Phúc",
    "vu": "s:President: Baldwin Lonsdale | g:Prime Minister: Charlot Salwai",
    "ye": "s:President: Abdrabbuh Mansur Hadi | g:Prime Minister: Ahmed Obeid bin Daghr",
    "za": "s:President: Jacob Zuma",
    "zm": "s:President: Edgar Lungu",
    "zw": "s:President: Robert Mugabe"
};
