/**
 * created by lap-hep-deb-use on 1/19/17.
 */

var names = {
    "id": "indonesia",
    "pg": "papua new guinea",
    "mx": "mexico",
    "ee": "estonia",
    "dz": "algeria",
    "ma": "morocco",
    "mr": "mauritania",
    "sn": "senegal",
    "gm": "gambia",
    "gw": "guinea-bissau",
    "gn": "guinea",
    "sl": "sierra leone",
    "lr": "liberia",
    "ci": "cote d'ivoire",
    "ml": "mali",
    "bf": "burkina faso",
    "ne": "niger",
    "gh": "ghana",
    "tg": "togo",
    "bj": "benin",
    "ng": "nigeria",
    "tn": "tunisia",
    "ly": "libya",
    "eg": "egypt",
    "td": "chad",
    "sd": "sudan",
    "cm": "cameroon",
    "er": "eritrea",
    "dj": "djibouti",
    "et": "ethiopia",
    "so": "somalia",
    "ye": "yemen",
    "cf": "central african republic",
    "st": "sao tome and principe",
    "gq": "equatorial guinea",
    "ga": "gabon",
    "cg": "congo",
    "ao": "angola",
    "cd": "congo",
    "rw": "rwanda",
    "bi": "burundi",
    "ug": "uganda",
    "ke": "kenya",
    "tz": "tanzania",
    "zm": "zambia",
    "mw": "malawi",
    "mz": "mozambique",
    "zw": "zimbabwe",
    "na": "namibia",
    "bw": "botswana",
    "sz": "swaziland",
    "ls": "lesotho",
    "za": "south africa",
    "gl": "greenland",
    "au": "australia",
    "nz": "new zealand",
    "nc": "new caledonia",
    "my": "malaysia",
    "bn": "brunei darussalam",
    "tl": "east timor",
    "sb": "solomon islands",
    "vu": "vanuatu",
    "fj": "fiji",
    "ph": "philippines",
    "cn": "china",
    "tw": "taiwan",
    "jp": "japan",
    "ru": "russian federation",
    "us": "united states of america",
    "mu": "mauritius",
    "re": "reunion",
    "mg": "madagascar",
    "km": "comoros",
    "sc": "seychelles",
    "mv": "maldives",
    "pt": "portugal",
    "es": "spain",
    "cv": "cape verde",
    "pf": "french polynesia",
    "kn": "saint kitts and nevis",
    "ag": "antigua and barbuda",
    "dm": "dominica",
    "lc": "saint lucia",
    "bb": "barbados",
    "gd": "grenada",
    "tt": "trinidad and tobago",
    "do": "dominican republic",
    "ht": "haiti",
    "fk": "falkland islands",
    "is": "iceland",
    "no": "norway",
    "lk": "sri lanka",
    "cu": "cuba",
    "bs": "bahamas",
    "jm": "jamaica",
    "ec": "ecuador",
    "ca": "canada",
    "gt": "guatemala",
    "hn": "honduras",
    "sv": "el salvador",
    "ni": "nicaragua",
    "cr": "costa rica",
    "pa": "panama",
    "co": "colombia",
    "ve": "venezuela",
    "gy": "guyana",
    "sr": "suriname",
    "gf": "french guiana",
    "pe": "peru",
    "bo": "bolivia",
    "py": "paraguay",
    "uy": "uruguay",
    "ar": "argentina",
    "cl": "chile",
    "br": "brazil",
    "bz": "belize",
    "mn": "mongolia",
    "kp": "north korea",
    "kr": "south korea",
    "kz": "kazakhstan",
    "tm": "turkmenistan",
    "uz": "uzbekistan",
    "tj": "tajikistan",
    "kg": "kyrgyz republic",
    "af": "afghanistan",
    "pk": "pakistan",
    "in": "india",
    "np": "nepal",
    "bt": "bhutan",
    "bd": "bangladesh",
    "mm": "myanmar",
    "th": "thailand",
    "kh": "cambodia",
    "la": "lao people's democratic republic",
    "vn": "vietnam",
    "ge": "georgia",
    "am": "armenia",
    "az": "azerbaijan",
    "ir": "iran",
    "tr": "turkey",
    "om": "oman",
    "ae": "united arab emirates",
    "qa": "qatar",
    "kw": "kuwait",
    "sa": "saudi arabia",
    "sy": "syrian arab republic",
    "iq": "iraq",
    "jo": "jordan",
    "lb": "lebanon",
    "il": "israel",
    "cy": "cyprus",
    "gb": "united kingdom",
    "ie": "ireland",
    "se": "sweden",
    "fi": "finland",
    "lv": "latvia",
    "lt": "lithuania",
    "by": "belarus",
    "pl": "poland",
    "it": "italy",
    "fr": "france",
    "nl": "netherlands",
    "be": "belgium",
    "de": "germany",
    "dk": "denmark",
    "ch": "switzerland",
    "cz": "czech republic",
    "sk": "slovakia",
    "at": "austria",
    "hu": "hungary",
    "si": "slovenia",
    "hr": "croatia",
    "ba": "bosnia and herzegovina",
    "mt": "malta",
    "ua": "ukraine",
    "md": "moldova",
    "ro": "romania",
    "rs": "serbia",
    "bg": "bulgaria",
    "al": "albania",
    "mk": "macedonia",
    "gr": "greece",
    "me": "montenegro",
    "vc": "saint vincent and the grenadines",
    "bh": "bahrain"
};

var name_countries = names;